### ISSUE TITLE
[RFE] Make it possible to link work items for polarion requirements

### ISSUE THREAD

**Issue by valaparthvi** [mkoura/dump2polarion#16]
Currently it is not possible to link work items to requirements. It would be nice to introduce this feature to dump2polarion. I'm willing to work on this if the features seems good.

**Comment by mkoura** [comment]
Hi Parthvi, it is already possible. In Polarion Importers it works the other way around. You link requirements to work items. Please take a look at https://github.com/mkoura/dump2polarion/blob/master/dump2polarion/exporters/testcases_exporter.py#L278
Multiple requirements that should be linked to the work item (test case) are passed as list of either strings (requirement id or name, based on "linked-items-lookup-method" settings) or dict. See https://github.com/mkoura/dump2polarion/blob/master/dump2polarion/exporters/testcases_exporter.py#L34

The data for dump2polarion is collected and prepared by the "pytest-polarion-collect" pytest plugin, the linked-items specific part is https://gitlab.com/mkourim/pytest-polarion-collect/-/blob/master/pytest_polarion_collect/utils.py#L195

The parsing of Polarion metadata is done by "polarion_docstrings" library, the part specific to linked-items is https://gitlab.com/mkourim/polarion_docstrings/-/blob/master/polarion_docstrings/parser.py#L320

In IQE the linking is already used by some plugins, I remember that HCCM has almost every work item linked to some requirement.
